services:
  glpiapp:
    container_name: "glpi"
    build:
      context: ".docker/app"
      args:
        PHP_VERSION: "8.4"
    restart: "unless-stopped"
    volumes:
      - ".:/var/www/glpi:rw"
    ports:
      - "8080:80"
      - "9637:9637"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - glpi-network
    depends_on:
      - dbglpi
  dbglpi:
    container_name: "dbglpi"
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - glpi-network
    volumes:
      - "./db:/var/lib/mysql"

networks:
  glpi-network:
    driver: bridge
