services:
  glpi-app:
    container_name: "glpi"
    build:
      context: ".docker/app"
      args:
        PHP_VERSION: "8.4"
    restart: "unless-stopped"
    volumes:
      - ".:/var/www/glpi:rw"
    ports:
      - "8080:80"
      - "9637:9637"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network:
      - glpi-network
  db-glpi:
    container_name: dbMysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    network:
      - glpi-network
    volumes:
      - "./db:/var/lib/mysql"

networks:
  glpi-network:
    driver: bridge
